// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDIqKtoR12i8HjH3tbYthToyBrAX-9el8',
    appId: '1:382650068012:web:121072727f719c4ebe3589',
    messagingSenderId: '382650068012',
    projectId: 'mobileai-3b687',
    authDomain: 'mobileai-3b687.firebaseapp.com',
    storageBucket: 'mobileai-3b687.appspot.com',
    measurementId: 'G-TW4EBETHXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmmVl_gvJ0UhOZkENH8kKfJECpSiAGCs8',
    appId: '1:382650068012:android:5c82d4e2147b6f92be3589',
    messagingSenderId: '382650068012',
    projectId: 'mobileai-3b687',
    storageBucket: 'mobileai-3b687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOnIZOdXzP6WqSlOkvkoeLgZ0mZuD79U4',
    appId: '1:382650068012:ios:77b6a887561867b5be3589',
    messagingSenderId: '382650068012',
    projectId: 'mobileai-3b687',
    storageBucket: 'mobileai-3b687.appspot.com',
    iosBundleId: 'com.example.flutterAiCcProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOnIZOdXzP6WqSlOkvkoeLgZ0mZuD79U4',
    appId: '1:382650068012:ios:9bcaa044ff561e9abe3589',
    messagingSenderId: '382650068012',
    projectId: 'mobileai-3b687',
    storageBucket: 'mobileai-3b687.appspot.com',
    iosBundleId: 'com.example.flutterAiCcProject.RunnerTests',
  );
}
